services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      device: /home/ycheroua/goinfre/mariadb
      o: bind

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/ycheroua/goinfre/wordpress
      o: bind
